### ISSUE TITLE
Need admin permission to add secret for GitHub Action

### ISSUE THREAD

**Issue by mstimberg** [OCNS/simselect#2]
Deployment on fly.io is now automatic via a [https://github.com/OCNS/simselect/actions/workflows/deploy.yml](https://github.com/OCNS/simselect/actions/workflows/deploy.yml), but it doesn't work yet since I have to set the API token as a "secret" for authentification. This requires admin rights on the repository, which I don't have at the moment. @sanjayankur31: I think you are the owner of the repo, could you please give me the permission so that I can provide the token?

**Comment by sanjayankur31** [comment]
Given you admin access now. Please close this ticket if that works.

**Comment by mstimberg** [comment]
Thanks, works like a charm (autodeploys on push to `main` now: https://github.com/OCNS/simselect/actions/runs/4719476958)
