### ISSUE TITLE
Acknowledge all types of contributions in a structured way (allcontributors.org)?

### ISSUE THREAD

**Issue by mstimberg** [OCNS/simselect#38]
Obviously, we do not have that many contributors yet, but it might be good to think about this early. Currently, one can see the code contributions for everyone that commited to the github repository easily, but in particular @elianecr's and @dissagaliyeva's contributions during earlier meetings/discussions are invisible. I have never used it in a project myself, but we could use the https://allcontributors.org framework, which generates a table of contributors in the README, also acknowledging contribution types such as "design" or "bug report", which are typically not visible as code contributions.

**Comment by sanjayankur31** [comment]
+1, I've been meaning to look into allcontributors.org. Will try and set it up here (if no one beats me to it).

**Comment by sanjayankur31** [comment]
Hrm, I can't seem to add it to this repo. It wants me to request it.

@appukuttan-shailesh : would you have the necessary org rights to add it please?

https://allcontributors.org/docs/en/bot/installation -> link at the top of the page, and then one needs to select the OCNS organization

**Comment by appukuttan-shailesh** [comment]
Already done :-)

**Comment by sanjayankur31** [comment]
awesome, thanks :100:

**Comment by sanjayankur31** [comment]
OK, that works, let me add everyone

@all-contributors
please add @mstimberg for ideas, projectManagement, research, review, test
please add @ree-gupta for code, content, data, maintenance, design, ideas, projectManagement, research, review, test
please add @dissagaliyeva for code, design, ideas, projectManagement, research
please add @elianecr for design, content, data, ideas, projectManagement, research
please add @brenthuisman  for code, content, data, maintenance, design, ideas, projectManagement, research, review, test
please add @sanjayankur31  for code, content, data, maintenance, design, ideas, projectManagement, research, review, test

If I've missed anyone for anything, please add them---you know what to do :)

The contribution list is here:
https://allcontributors.org/docs/en/emoji-key

**Comment by sanjayankur31** [comment]
Meh, it isnt' smart enough to do everything in one PR, so I've got to drop a comment, merge the PR and repeat. Sorry, this is going to be noisy :( 

@all-contributors please add @ree-gupta for code, content, data, maintenance, design, ideas, projectManagement, research, review, test

**Comment by sanjayankur31** [comment]
@all-contributors please add @sanjayankur31 for code, content, data, maintenance, design, ideas, projectManagement, research, review, test
