### ISSUE TITLE
Data/UI: "Getting started" or "Tutorials" link, plus filter

### ISSUE THREAD

**Issue by brenthuisman** [OCNS/simselect#49]
- Add a link to a "Getting started" or "Tutorials" page for each tool, where Getting started means: not (just) installing but also showing a short demo. Or a link to a tutorials index.
- Let users filter on tools with "Getting started" links.

**Comment by sanjayankur31** [comment]
Also:

- examples (maybe 2 each)
- published models (maybe 2 each)
- linked paper

**Comment by sanjayankur31** [comment]
We'll link to the documentation for each tool, and hope that tools have getting started documentation. We'll revisit this later.
